apiVersion: v1
kind: Service
metadata:
  name: vm-20gb-ssh
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  selector:
    kubevirt.io/domain: vm-20gb